version: '2'
services:
  postgres:
    container_name: ${APP_PREFIX}-postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${APP_PREFIX}
      - POSTGRES_PASSWORD=${APP_PREFIX}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:delegated


  mysql:
    container_name: ${APP_PREFIX}-mariadb
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_PREFIX}
      - MYSQL_USER=${APP_PREFIX}
      - MYSQL_PASSWORD=${APP_PREFIX}
      - MYSQL_DATABASE=${APP_PREFIX}
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306
