version: '2'
services:
  mysql:
    container_name: ${APP_PREFIX}-mariadb
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_PREFIX}
      - MYSQL_USER=${APP_PREFIX}
      - MYSQL_PASSWORD=${APP_PREFIX}
      - MYSQL_DATABASE=${APP_PREFIX}
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306
